### PR TITLE
Merge python3

### PR DESCRIPTION
**Pull request by ernix**
Cover ca93a61 while resolving merge conflict.

### CODE REVIEW

**Comment by Matmaus** [comment]
Isn't commit #81346e1 the only one needed? I think we do not need others. It seems to be a mess of commits changing only a simple thing to me.

**Comment by ernix** [comment]
@Matmaus Yes, it is. We can just cherry-pick 81346e1 if you want.  Do you want to keep tree diagram as simple as possible?

**Comment by Matmaus** [comment]
> @Matmaus Yes, it is. We can just cherry-pick [81346e1](https://github.com/Matmaus/LnkParse3/commit/81346e199929d803d300a467c184c4fc9671c4d1) if you want. Do you want to keep tree diagram as simple as possible?

Yes, I think the simpler is better, and in this case, it can be much simpler.

**Comment by ernix** [comment]
@Matmaus Got it, wait a sec.

**Pull request closed without merging**
